### ISSUE TITLE
Suggestions for JS Lessons 1 and 2

### ISSUE THREAD

**Issue by IsmaelMartinez** [CodeYourFuture/syllabus-archive#16]
Hi, 

I think I might have put it in a different way than expected but created pull request #15 and #14 for the 1st to lessons of javascript. 

Not much added a part from plenty of links to information.

Let me konw if you prefer me to add this information in the "issues" section and I will do it like that next time.

Thanks!

**Comment by tvooo** [comment]
Hi Ismael,
thanks for this! Just to avoid confusion and duplicate work in the future, we should maybe coordinate when we work on the same lessons. I fully agree with your additions, I've added them in similar form in my fork. Maybe we can divide the work?

Cheers

**Comment by IsmaelMartinez** [comment]
Hi @tvooo ,

I don't tend to have much time to look into other things rather than work, but looks like I might be able to do a bit of "work" in that are this week. 

As I am not the person teaching the class, I am happy to review and/or suggest, but, at the end, you people that are running the class feel free to select what bests suits you!!

I can add some small exercises and try to explain why things like that happen (like why 'false' == false is false, why  1+2+"3" != "1"+2+3... and similar.)

Or do you want me to look at an specific area??

Ta

**Comment by tvooo** [comment]
No, you just seemed eager to do things, and although I'm assigned to JS lesson 1 I won't be able to do much before the weekend. I just wanted to avoid duplicate work, that's all. If you don't have time, don't worry 👍
