### ISSUE TITLE
JavaScript III: Week 10 - Good Code, TDD (additional material)

### ISSUE THREAD

**Issue by christopherallanperry** [CodeYourFuture/syllabus-archive#183]
As a way of giving the students additional practice for TDD, I'd like to propose that we include Marc Littlemore's (BBC) free 7-lesson [http://www.marclittlemore.com/courses/javascript-testing-made-easy/]("JavaScript Testing Made Easy") course in the homework section of Week 10.

It makes use of Mocha/Chai/Sinon rather than Jest, but it will give the students some exposure to alternative testing frameworks, show them that these have a great deal of commonality, and should be nothing to be concerned about.

I have spoken to Marc on the use of the course for CYF and he was more than happy that we make use of it. It includes a daily email for each lesson with a clear set of instructions to follow, a set of YouTube videos and an associated GitHub repository.

**Comment by christopherallanperry** [comment]
Thanks for merging this @kkarimi - I'm not seeing it appear on the live syllabus though, but can't see an obvious reason why that would be. Can you have a look?

**Comment by kkarimi** [comment]
@christopherallanperry no prob, looks like one of the commits broke the build yesterday which meant it did not publish. It's [there](https://codeyourfuture.github.io/syllabus-master/js-core-3/week-10/lesson.html#homework) now

**Comment by christopherallanperry** [comment]
@kkarimi : Thanks Kash
