### ISSUE TITLE
Links on Introduction page

### ISSUE THREAD

**Issue by slacle** [CodeYourFuture/syllabus-archive#304]
**1.**
Right now, the link to Code Your Future website on the first paragraph of the [Introduction page](https://codeyourfuture.github.io/syllabus-master/) links to .co which then redirects to .io.

Shouldn't it be linking to .io right away?

**2.**
On the _Students_ section, there is a link to the summary file which is broken.

Currently it is linked to: https://codeyourfuture.github.io/syllabus-master/SUMMARY.md which doesn't exist.

Maybe it could be linked to: https://github.com/CodeYourFuture/syllabus/blob/master/SUMMARY.md

**Comment by bonboh** [comment]
Hi, thanks for the feedback!

1. I've updated the Introduction page to use https://codeyourfuture.io/

2. On review, it doesn't make sense to link SUMMARY.md since its contents are exactly what are shown in the left hand menu. I've removed it.

Let us know if you find any other issues.
