### ISSUE TITLE
[js3-project] github pages doesn't use index.html as default root page

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/syllabus-archive#383]
Using the template, when I push to github pages, https://illicitonion.github.io/tv-show-dom-project/ is a 404

https://illicitonion.github.io/tv-show-dom-project/index.html works fine

If I rename to index.htm the bare / works

**Comment by nbogie** [comment]
Thanks!A good reason to use netlify. 
This works for me most of the time.  the codeyourfuture/tv-show-dom-project didn't deploy initially (404) but did after some time.  
I just ran through the instructions and it worked fine for me.  

Is it possible that the rename to index.htm is more just giving the machine a kick, than an actual solution.

I'm a netlify fan, and the students have already used it (very briefly) in the course, so we'll probably just go in that direction.  (So don't spend time digging into this github pages issue.)

**Comment by illicitonion** [comment]
Bleh, yeah, I've done a bunch of renaming and trying, and it looks just non-deterministic... I was in a state at some point where `/index.html` reliably _did_ work but `/` didn't, for multiple minutes :S

Probably worth noting for volunteers somewhere, if we don't switch to netlify :)

**Comment by nbogie** [comment]
(We switched to netlify)
