### ISSUE TITLE
JavaScript Core 1 revisions

### ISSUE THREAD

**Issue by r-darby** [CodeYourFuture/syllabus-archive#420]
Rework JS1 so it is suitable for students with no previous coding experience.

Following these principles -
1. Don't use anything in examples or exercises which hasn't been specifically taught yet
2. Build up students' confidence & comprehension by starting each section with an easy exercise and building slowly
3. Use simple English when possible

**Comment by djgrant** [comment]
Good criteria. Perhaps we should add this to the repo's contributing guidelines.
